### ISSUE TITLE
Critique comment from Weiyi Li

### ISSUE THREAD

**Issue by wyliadrian** [RuiLi7222/BIS687-Capstone_Project_Team5#10]
Great research question and presentation! It was very inspiring to relate nutrition intake with overall health for elder people. I was wondering how would you generate the nutrition measurement score from the UK Biobank dataset and how to determine the relative weight for each factor? Thanks!

**Comment by RuiLi7222** [comment]
Hi Weiyi, thank you so much for your participation. Measuring the diet quality will be the key to our project. As we mentioned in the presentation, we will use five different widely used diet quality indices to measure both the nutrition quality and the variability. As for the details, we are still exploring. If you have any other questions, please feel free to ask.
