### ISSUE TITLE
Critique comments from Jiayi

### ISSUE THREAD

**Issue by zjy0419** [RuiLi7222/BIS687-Capstone_Project_Team5#12]
I think this study is complete and meaningful. Here are some possible imperfections I can find. 

As it happens, the questions I want to raise have already been written in Potential Problems and Alternative Approaches section.  I am looking forward to how the nonlinear study should be carried out, whether the results will be different, whether Simpson's paradox will emerge, etc. 

In addition, I am also interested in mediation analysis. My understanding is that you use univariate analysis, so I wonder whether you consider the comprehensive impact of multiple Mediators.

**Comment by lizsul2000** [comment]
We will conduct multivariate analysis including multiple possible confounders and mediators as covariates.

Thank you for your question.
