### ISSUE TITLE
Critique comment from Dr. Kane

### ISSUE THREAD

**Issue by kaneplusplus** [RuiLi7222/BIS687-Capstone_Project_Team5#7]
Great presentation.

Comments:

1. Can you say why you picked the 65 year cut-off?
2. Do you think screen time increases with age - people become more sedetary? If not, it is generational?
3. When you are looking at the CATE changes, how will you know if the difference is significant?

**Comment by RuiLi7222** [comment]
Hi Dr. Kane, thank you for your comments. We pick 65 years as the cut-off because many researches about older people choose this age range. We will address the second and third questions in our proposal.
