### ISSUE TITLE
Critique comment from Zexiang Li

### ISSUE THREAD

**Issue by zexiangli** [RuiLi7222/BIS687-Capstone_Project_Team5#9]
Thanks for the excellent presentation. I wondered what's the advantage of splitting the research question into two specific aims compared to directly estimating the association between screen time and overall health outcomes. It would be helpful for me to understand it better if you explained more about this in the specific aim section.  Thanks!

**Comment by RuiLi7222** [comment]
Hi Zexiang, thank you for your suggestion! We will cover it in our proposal.
